services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-app
    ports:
      - "3000:3000"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt # Добавлен том для сертификатов
    ports:
      - "80:80"
      - "443:443" # Открыт порт для HTTPS
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
